name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          dockerfile: containers/Dockerfile
          image: nagarajanp/smvplot
          tags: latest, ${{ github.ref }}

          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
